#!/bin/bash

cd $(dirname $0)/..

function fail {
    echo "ERROR: $1"
    exit 1
}

java -version 2>&1 || fail "Java is required"

mkdir -p parser

java \
  -Xmx500M \
  -cp ./g4/antlr-4.13.1-complete.jar \
  org.antlr.v4.Tool \
  -Dlanguage=Go \
  -Xexact-output-dir \
  -o parser \
  g4/PlSqlLexer.g4 \
  g4/PlSqlParser.g4 \
  || fail "Failed to generate"
