name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: "temurin"
      - run: ./g4/parser-gen
      - uses: actions/setup-go@v4
        with:
          go-version: "1.21"
      - run: go test ./...
